### ISSUE TITLE
Error when writing functional tests with Django using: StaticLiveServerTestCase

### ISSUE THREAD

**Issue by detectedstealth** [ojii/django-sekizai#52]
```
 "You must enable the 'sekizai.context_processors.sekizai' template "
TemplateSyntaxError: You must enable the 'sekizai.context_processors.sekizai' template context processor or use 'sekizai.context.SekizaiContext' to render your templates.
```

Meanwhile ``sekizai.context_processors.sekizai`` is in the template context processors and the site works when running using ``manage.py runserver``. 

However when running using ``manage.py`` test with a simple test like the following I get the above error:

```python
def test_home_page_title(self):
        title = 'Learn Languages Online'
        self.browser.get(self.server_url)
        self.assertIn(title, self.browser.title, self.browser.title)
```

Located in a different base file inheriting from ``StaticLiveServerTestCase``.

```python
from selenium import web driver

self.server_url = self.live_server_url
self.browser = webdriver.PhantomJS()
self.browser.set_window_size(800,600)
self.browser.implicitly_wait(DEFAULT_WAIT)
```

Is there some special configuration that is required in order to get django-sekizai working with Django's default testing framework? Doing a google search I see others have been running into this same issue, however the solutions required django-cms which we are not using.

**Comment by ojii** [comment]
You don't need django CMS, what you need is to follow the error you're getting. If indeed ``sekizai_context_processors.sekizai`` is in your ``TEMPLATE_CONTEXT_PROCESSORS``, you need to use ``RequestContext`` to render your template.

Alternatively you can use ``sekizai.context.SekizaiContext`` (instead of ``RequestContext``).

Running live-server tests or not has nothing to do with it.

**Comment by detectedstealth** [comment]
TEMPLATE_CONTEXT_PROCESSORS =  (
   ...
    "sekizai.context_processors.sekizai",
   ...
)

Are you saying to use RequestContext in my test methods? Or in my views? If in the views then in theory regardless of tests the site should be failing when browsing a page which it is not. Live site: https://www.lingq.com is using this package. 

If it is in the test methods themselves you are referring to can you provide a simple example of how to properly getting a test to run? As I was assuming that self.browser.get(self.server_url) should be loading the view which would handle things exactly how the live site is working.

**Comment by detectedstealth** [comment]
Ok so my settings has TEMPLATE_CONTEXT_PROCESSORS
```
TEMPLATE_CONTEXT_PROCESSORS = DEFAULT_SETTINGS.TEMPLATE_CONTEXT_PROCESSORS + (
    "django.core.context_processors.request",
    "lingq.processors.config_injector",
    "lingq.processors.stats_injector",
    "lingq_metrics.context_processors.metrics_tags",
    "lingq_wall.context_processors.privacy",
    "lingq_wall.context_processors.media",
    "sekizai.context_processors.sekizai",  # <-----------------------------
    "allauth.account.context_processors.account",
    "allauth.socialaccount.context_processors.socialaccount",
)
```
The view returns a RequestContext
```
def index(request):
    native_lang = get_native_language()
    video_url = Locale.get(native_lang).urls.get('intro', '7MC5NaKdZdg')
    teaser = getattr(Locale.get(native_lang), 'teaser', None)
    return render_to_response('lingq/index.html', {'video_url': video_url, 'teaser': teaser, 'native_lang': native_lang}, context_instance=RequestContext(request))
```

When viewing live at http://lingq.com it works as expected. When running a simple test
```
## -*- coding: utf-8 -*-
from selenium import webdriver
from django.core.urlresolvers import reverse
from django.contrib.staticfiles.testing import LiveServerTestCase  
 
class HomeNewVisitorTest(LiveServerTestCase): 
 
    def setUp(self):
        self.browser = webdriver.PhantomJS()
        self.browser.set_window_size(800,600)
        self.browser.implicitly_wait(3)
 
    def tearDown(self):
        self.browser.quit()
 
    def get_full_url(self, namespace):
        return self.live_server_url + reverse(namespace)
 
    def test_home_title(self):
        self.browser.get(self.get_full_url("home"))
        self.assertIn("TaskBuster", self.browser.title)
```
It fails with the following:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/vagrant/eggs/Django-1.8.3-py2.7.egg/django/test/testcases.py", line 1103, in __call__
    return self.application(environ, start_response)
  File "/vagrant/eggs/Django-1.8.3-py2.7.egg/django/test/testcases.py", line 1103, in __call__
    return self.application(environ, start_response)
  File "/vagrant/eggs/Django-1.8.3-py2.7.egg/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/vagrant/eggs/Django-1.8.3-py2.7.egg/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/vagrant/eggs/Django-1.8.3-py2.7.egg/django/core/handlers/base.py", line 268, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/vagrant/eggs/Django-1.8.3-py2.7.egg/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/vagrant/eggs/Django-1.8.3-py2.7.egg/django/views/defaults.py", line 45, in server_error
    return http.HttpResponseServerError(template.render())
  File "/vagrant/eggs/Django-1.8.3-py2.7.egg/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/vagrant/eggs/Django-1.8.3-py2.7.egg/django/template/base.py", line 209, in render
    return self._render(context)
  File "/vagrant/eggs/Django-1.8.3-py2.7.egg/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/vagrant/eggs/Django-1.8.3-py2.7.egg/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/vagrant/eggs/Django-1.8.3-py2.7.egg/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/vagrant/eggs/Django-1.8.3-py2.7.egg/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/vagrant/eggs/Django-1.8.3-py2.7.egg/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/vagrant/eggs/Django-1.8.3-py2.7.egg/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/vagrant/eggs/Django-1.8.3-py2.7.egg/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/vagrant/parts/django-sekizai/sekizai/templatetags/sekizai_tags.py", line 61, in render
    if validate_context(context):
  File "/vagrant/parts/django-sekizai/sekizai/templatetags/sekizai_tags.py", line 30, in validate_context
    "You must enable the 'sekizai.context_processors.sekizai' template "
TemplateSyntaxError: You must enable the 'sekizai.context_processors.sekizai' template context processor or use 'sekizai.context.SekizaiContext' to render your templates.
```

**Comment by ojii** [comment]
I see, the naughty line is this: ``    return http.HttpResponseServerError(template.render())``

Your view 500s in your test, triggering the default Django error view. This renders your ``500.html`` file. In the ``500.html`` you are **not** allowed to use sekizai. (maybe look into https://github.com/ojii/django-statictemplate if you *really* need sekizai)

**Comment by detectedstealth** [comment]
Good catch that is exactly what the issue was. A base template that depended on sekizai was inherited in 500.html I removed it and now the error is gone.

Thanks.
